# pubspec.yaml

name: radiont
description: A modern, abstract radio application.
publish_to: 'none' 
version: 1.1.3+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  intl: ^0.18.1
  glass_kit: ^3.0.0
  shared_preferences: ^2.2.2
  glassmorphism: ^3.0.0
  google_fonts: ^6.2.1
  simple_animations: ^5.1.0
  wakelock_plus: ^1.3.2
  http: ^1.4.0
  just_audio: ^0.10.4
  volume_controller: ^2.0.0
  #just_audio_background: ^0.9.6  # Frissített verzió
  permission_handler: ^11.3.1
  just_audio_background: ^0.0.1-beta.11

just_audio_background: 
  git:
    url: https://github.com/ryanheise/just_audio_background.git
    ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-Regular.ttf
        - asset: assets/fonts/Orbitron-Bold.ttf
          weight: 700