name: radiont
description: A modern, radio application.
publish_to: 'none' 
version: 1.2.5+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State management és segédprogramok
  provider: ^6.1.1
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  permission_handler: ^11.3.1
  google_fonts: ^6.2.1
  
  # UI csomagok
  glass_kit: ^3.0.0
  glassmorphism: ^3.0.0
  simple_animations: ^5.1.0
  loading_animation_widget: ^1.2.1

  # Audio és vezérlés
  just_audio: ^0.9.36 # Javasolt a legfrissebb stabil verzió használata
  just_audio_background: ^0.0.1-beta.11 # A meglévő béta, de működik
  wakelock_plus: ^1.3.2
  volume_controller: ^2.0.0
  
  # Egyéb
  http: ^1.2.0 # Javasolt frissítés
  flutter_launcher_icons: "^0.13.1"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Javasolt frissítés

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-Regular.ttf
        - asset: assets/fonts/Orbitron-Bold.ttf
          weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#003838"
  adaptive_icon_foreground: "assets/icon/adapt_icon.png"